# Generated by Django 4.0.3 on 2022-03-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_chainshop_shopchain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopchain',
            name='unique_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
