# Generated by Django 4.0.3 on 2022-03-15 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_remove_product_code_product_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('key', models.CharField(default='p4shkdGMMtpbDDdTRIKl71zWR10vO4Sa', max_length=32, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopchain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopchain',
            name='managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
