# Generated by Django 4.0.3 on 2022-03-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_applicationtoken_alter_shop_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationToken',
        ),
    ]
