# Generated by Django 4.0.3 on 2022-03-13 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2500)),
                ('unique_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('managers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
