# Generated by Django 4.0.3 on 2022-03-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='key',
            field=models.CharField(default='f8sKvrMIOAb2dVo5mf4FNvm1Q9GafD0b', editable=False, max_length=32, unique=True),
        ),
    ]
