# Generated by Django 4.0.3 on 2022-03-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_applicationtoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='key',
            field=models.CharField(default='MVUjJwy9kiKZTskEHrkijvDIzzFYN3g8', editable=False, max_length=32, unique=True),
        ),
    ]
