# Generated by Django 4.0.3 on 2022-03-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_applicationtoken_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtoken',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationtoken',
            name='key',
            field=models.CharField(default='VrNUHNomVO62GUV9UUnjRdFj0zlwZYJS', editable=False, max_length=32, unique=True),
        ),
    ]
