# Generated by Django 4.0.3 on 2022-03-20 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0006_applicationtoken_active_alter_applicationtoken_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtoken',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationtoken',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationtoken',
            name='key',
            field=models.CharField(default='XJFqjHrA3wr6lq9S3b19yt86grnIJTCd', editable=False, max_length=32, unique=True),
        ),
    ]
